worker_processes 1;
error_log stderr;
include /usr/share/nginx/modules-available/mod-http-fancyindex.conf;

events {
	worker_connections 256;
}

http {
	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	access_log syslog:server=unix:/dev/log;

	gzip on;

	include /etc/nginx/conf.d/*.conf;

	server {
		include listen.conf;
		root /home/jnooree;

		try_files $uri $uri/ =404;
		index index.html index.htm;

		fancyindex on;
		fancyindex_exact_size off;
		fancyindex_localtime on;
		fancyindex_time_format "%F %I:%M %p";
	}
}
